# Generated by Django 3.2.6 on 2021-08-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testques', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.ManyToManyField(to='testques.Group'),
        ),
    ]
