# Generated by Django 3.2.6 on 2021-08-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testques', '0003_rename_question_question_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='question',
            field=models.ManyToManyField(to='testques.Question'),
        ),
    ]
