# Generated by Django 3.2.6 on 2021-08-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testques', '0004_auto_20210815_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='selected_count',
            field=models.IntegerField(default=0),
        ),
    ]
